/**
 * @category Assert
 */
export interface AssertErrorInit {
	/** Failure description. Falls back to a generic message when omitted. */
	message?: string;
	/** Value produced by the code under test. */
	actual?: unknown;
	/** Value the assertion compared against. */
	expected?: unknown;
	/** Assert method that raised the error, e.g. `'deepEqual'`. */
	operator?: string;
	/**
	 * `true` when `message` was generated by the assert method rather than
	 * provided by the caller.
	 */
	generatedMessage?: boolean;
}
